// Copyright (c) 2026 Ivan Murzak. Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the repository root for more information.

#include "Tools/UnrealMcpSkillTools.h"

#include "UnrealMcpLog.h"
#include "UnrealMcpSchema.h"
#include "UnrealMcpToolRegistry.h"

#include "Dom/JsonObject.h"
#include "Dom/JsonValue.h"
#include "HAL/FileManager.h"
#include "Interfaces/IPluginManager.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"

namespace UnrealMcpSkillTools
{
	const TCHAR* const SkillCreateToolId = TEXT("unreal-skill-create");

	namespace
	{
		// Unity-build ODR rule: every helper below is namespace-private to this file's anonymous namespace,
		// but the module is unity-built, so the names must still be unique across the whole module. The
		// `Skills` prefix is this family's unique stem (see CLAUDE.md "Unity-build ODR rule").

		/** The generated-file banner. Kept in one place so the specs and the generator cannot drift. */
		const TCHAR* const SkillsGeneratedBanner =
			TEXT("// GENERATED by the `unreal-skill-create` MCP system tool (docs/ARCHITECTURE.md §2.4).\n")
			TEXT("// Hand-editing is fine — this file is ordinary plugin source and is never regenerated in place.\n")
			TEXT("// It self-registers through FUnrealMcpGeneratedSkillRegistrar, so NO other file needs editing;\n")
			TEXT("// deleting this file (and rebuilding) removes the tool.\n");

		/** The copyright one-liner every file in this repo starts with (conventions.md). */
		const TCHAR* const SkillsCopyrightHeader =
			TEXT("// Copyright (c) 2026 Ivan Murzak. Licensed under the Apache License, Version 2.0.\n")
			TEXT("// See the LICENSE file in the repository root for more information.\n");

		/** The fluent builder call that declares one parameter of the given JSON type. */
		FString SkillsParamBuilderCall(const FSkillParamSpec& Param)
		{
			FString Method = TEXT("ParamString");
			if (Param.Type == TEXT("integer"))
				Method = TEXT("ParamInt");
			else if (Param.Type == TEXT("number"))
				Method = TEXT("ParamNumber");
			else if (Param.Type == TEXT("boolean"))
				Method = TEXT("ParamBool");

			FString Call = FString::Printf(TEXT("\t\t\t.%s(TEXT(\"%s\"), TEXT(\"%s\")"),
				*Method, *EscapeCppStringLiteral(Param.Name), *EscapeCppStringLiteral(Param.Description));
			if (Param.bRequired)
				Call += TEXT(", EUnrealMcpParamRequirement::Required");
			Call += TEXT(")\n");
			return Call;
		}

		/** Re-indent a caller-supplied handler body to the generated lambda's depth, preserving blank lines. */
		FString SkillsIndentBody(const FString& Body)
		{
			TArray<FString> Lines;
			// Normalize CRLF first so a Windows-authored body does not leave stray '\r' inside the file.
			FString Normalized = Body;
			Normalized.ReplaceInline(TEXT("\r\n"), TEXT("\n"));
			Normalized.ReplaceInline(TEXT("\r"), TEXT("\n"));
			Normalized.ParseIntoArray(Lines, TEXT("\n"), /*InCullEmpty*/ false);

			FString Out;
			for (const FString& Line : Lines)
			{
				if (Line.TrimStartAndEnd().IsEmpty())
					Out += TEXT("\n");
				else
					Out += FString::Printf(TEXT("\t\t\t\t%s\n"), *Line);
			}
			return Out;
		}

		/** The JSON Schema for the `params` array argument of `unreal-skill-create`. */
		TSharedPtr<FJsonObject> SkillsMakeParamsSchema()
		{
			TSharedPtr<FJsonObject> Properties = MakeShared<FJsonObject>();
			Properties->SetObjectField(TEXT("name"), FUnrealMcpSchema::TypedSchema(
				TEXT("string"), TEXT("Parameter name (camelCase), e.g. 'targetName'.")));
			Properties->SetObjectField(TEXT("type"), FUnrealMcpSchema::TypedSchema(
				TEXT("string"), TEXT("JSON type: 'string' (default), 'integer', 'number' or 'boolean'.")));
			Properties->SetObjectField(TEXT("description"), FUnrealMcpSchema::TypedSchema(
				TEXT("string"), TEXT("What the parameter means; shown to the AI in the tool schema.")));
			Properties->SetObjectField(TEXT("required"), FUnrealMcpSchema::TypedSchema(
				TEXT("boolean"), TEXT("Whether the parameter is required. Default false.")));

			TSharedPtr<FJsonObject> Items = MakeShared<FJsonObject>();
			Items->SetStringField(TEXT("type"), TEXT("object"));
			Items->SetObjectField(TEXT("properties"), Properties);
			TArray<TSharedPtr<FJsonValue>> ItemRequired;
			ItemRequired.Add(MakeShared<FJsonValueString>(TEXT("name")));
			Items->SetArrayField(TEXT("required"), ItemRequired);

			TSharedPtr<FJsonObject> Schema = MakeShared<FJsonObject>();
			Schema->SetStringField(TEXT("type"), TEXT("array"));
			Schema->SetStringField(TEXT("description"),
				TEXT("Declared parameters of the new tool. Each entry is { name, type?, description?, required? }."));
			Schema->SetObjectField(TEXT("items"), Items);
			return Schema;
		}

		/** Read the `params` argument into typed specs. Returns false + a reason on a malformed entry. */
		bool SkillsParseParams(const FUnrealMcpToolCall& Call, TArray<FSkillParamSpec>& OutParams, FString& OutError)
		{
			const TArray<TSharedPtr<FJsonValue>>* Array = nullptr;
			if (!Call.Arguments->TryGetArrayField(TEXT("params"), Array) || Array == nullptr)
				return true; // absent is fine — a parameterless tool

			for (const TSharedPtr<FJsonValue>& Value : *Array)
			{
				const TSharedPtr<FJsonObject>* Obj = nullptr;
				if (!Value.IsValid() || !Value->TryGetObject(Obj) || Obj == nullptr || !Obj->IsValid())
				{
					OutError = TEXT("Every 'params' entry must be an object like { \"name\": \"x\", \"type\": \"string\" }.");
					return false;
				}

				FSkillParamSpec Spec;
				(*Obj)->TryGetStringField(TEXT("name"), Spec.Name);
				FString Type;
				if ((*Obj)->TryGetStringField(TEXT("type"), Type) && !Type.IsEmpty())
					Spec.Type = Type.ToLower();
				(*Obj)->TryGetStringField(TEXT("description"), Spec.Description);
				bool bRequired = false;
				if ((*Obj)->TryGetBoolField(TEXT("required"), bRequired))
					Spec.bRequired = bRequired;
				OutParams.Add(MoveTemp(Spec));
			}
			return true;
		}
	}

	// --- Pure helpers ------------------------------------------------------------------------------

	FString EscapeCppStringLiteral(const FString& In)
	{
		FString Out = In;
		Out.ReplaceInline(TEXT("\\"), TEXT("\\\\"));
		Out.ReplaceInline(TEXT("\""), TEXT("\\\""));
		Out.ReplaceInline(TEXT("\r\n"), TEXT("\\n"));
		Out.ReplaceInline(TEXT("\r"), TEXT("\\n"));
		Out.ReplaceInline(TEXT("\n"), TEXT("\\n"));
		Out.ReplaceInline(TEXT("\t"), TEXT("\\t"));
		return Out;
	}

	bool IsSupportedSkillParamType(const FString& Type)
	{
		return Type == TEXT("string") || Type == TEXT("integer") || Type == TEXT("number") || Type == TEXT("boolean");
	}

	FString SkillSymbolFromToolId(const FString& ToolId)
	{
		FString Symbol;
		bool bUpperNext = true;
		for (const TCHAR Ch : ToolId)
		{
			if (Ch == TEXT('-'))
			{
				bUpperNext = true;
				continue;
			}
			Symbol.AppendChar(bUpperNext ? FChar::ToUpper(Ch) : Ch);
			bUpperNext = false;
		}
		return Symbol;
	}

	FString DefaultTitleFromToolId(const FString& ToolId)
	{
		TArray<FString> Words;
		ToolId.ParseIntoArray(Words, TEXT("-"), /*InCullEmpty*/ true);
		FString Title;
		for (const FString& Word : Words)
		{
			if (!Title.IsEmpty())
				Title += TEXT(" ");
			Title += Word.Left(1).ToUpper() + Word.RightChop(1);
		}
		return Title;
	}

	FString SkillFileNameFromToolId(const FString& ToolId)
	{
		return FString::Printf(TEXT("UnrealMcpSkill_%s.cpp"), *SkillSymbolFromToolId(ToolId));
	}

	bool ValidateSkillSpec(const FSkillSpec& Spec, FString& OutError)
	{
		// Reuse the registry's OWN kebab-case predicate rather than re-deriving it: a name this rejects would
		// be dropped at registration time anyway, and having two patterns is how they drift apart.
		if (!FUnrealMcpToolRegistry::IsValidToolName(Spec.ToolId))
		{
			OutError = FString::Printf(
				TEXT("'%s' is not a valid tool id. Use kebab-case: lowercase letters/digits with single internal hyphens, e.g. 'my-skill'."),
				*Spec.ToolId);
			return false;
		}
		if (Spec.Description.TrimStartAndEnd().IsEmpty())
		{
			OutError = TEXT("'description' is required — it is what the AI reads to decide whether to call the tool.");
			return false;
		}
		if (Spec.Body.TrimStartAndEnd().IsEmpty())
		{
			OutError = TEXT("'body' is required — the C++ statements of the handler, ending in a `return FUnrealMcpToolResult::...;`.");
			return false;
		}

		TSet<FString> SeenNames;
		for (const FSkillParamSpec& Param : Spec.Params)
		{
			if (Param.Name.IsEmpty())
			{
				OutError = TEXT("Every declared parameter needs a non-empty 'name'.");
				return false;
			}
			// The name is embedded in a TEXT("...") literal AND used as a JSON Schema property key; keep it to a
			// plain identifier so neither the generated C++ nor the schema can be broken by an exotic name.
			for (const TCHAR Ch : Param.Name)
			{
				if (!FChar::IsAlnum(Ch) && Ch != TEXT('_'))
				{
					OutError = FString::Printf(
						TEXT("Parameter name '%s' must contain only letters, digits and underscores."), *Param.Name);
					return false;
				}
			}
			if (FChar::IsDigit(Param.Name[0]))
			{
				OutError = FString::Printf(TEXT("Parameter name '%s' must not start with a digit."), *Param.Name);
				return false;
			}
			if (!IsSupportedSkillParamType(Param.Type))
			{
				OutError = FString::Printf(
					TEXT("Parameter '%s' has unsupported type '%s'. Use string, integer, number or boolean."),
					*Param.Name, *Param.Type);
				return false;
			}
			bool bAlreadySeen = false;
			SeenNames.Add(Param.Name, &bAlreadySeen);
			if (bAlreadySeen)
			{
				OutError = FString::Printf(TEXT("Duplicate parameter name '%s'."), *Param.Name);
				return false;
			}
		}
		return true;
	}

	FString BuildSkillSourceCode(const FSkillSpec& Spec)
	{
		const FString Symbol = SkillSymbolFromToolId(Spec.ToolId);
		const FString Title = Spec.Title.IsEmpty() ? DefaultTitleFromToolId(Spec.ToolId) : Spec.Title;

		FString Out;
		Out += SkillsCopyrightHeader;
		Out += TEXT("\n");
		Out += SkillsGeneratedBanner;
		Out += TEXT("\n");
		Out += TEXT("#include \"Tools/UnrealMcpGeneratedSkills.h\"\n");
		Out += TEXT("#include \"UnrealMcpToolRegistry.h\"\n");
		Out += TEXT("\n");
		// A tool-id-derived namespace keeps every generated symbol unique in the unity build (CLAUDE.md ODR rule).
		Out += FString::Printf(TEXT("namespace UnrealMcpGeneratedSkill_%s\n{\n"), *Symbol);
		Out += TEXT("\tstatic void Register(FUnrealMcpToolRegistry& Registry)\n\t{\n");
		Out += FString::Printf(TEXT("\t\tRegistry.Tool(TEXT(\"%s\"))\n"), *EscapeCppStringLiteral(Spec.ToolId));
		Out += FString::Printf(TEXT("\t\t\t.Title(TEXT(\"%s\"))\n"), *EscapeCppStringLiteral(Title));
		Out += FString::Printf(TEXT("\t\t\t.Description(TEXT(\"%s\"))\n"), *EscapeCppStringLiteral(Spec.Description));
		if (!Spec.SkillDescription.IsEmpty())
		{
			Out += FString::Printf(TEXT("\t\t\t.SkillDescription(TEXT(\"%s\"))\n"),
				*EscapeCppStringLiteral(Spec.SkillDescription));
		}
		for (const FSkillParamSpec& Param : Spec.Params)
			Out += SkillsParamBuilderCall(Param);
		if (Spec.bReadOnlyHint)
			Out += TEXT("\t\t\t.ReadOnlyHint(true)\n");
		if (Spec.bDestructiveHint)
			Out += TEXT("\t\t\t.DestructiveHint(true)\n");
		if (Spec.bIdempotentHint)
			Out += TEXT("\t\t\t.IdempotentHint(true)\n");
		Out += TEXT("\t\t\t.Handle([](const FUnrealMcpToolCall& Call) -> FUnrealMcpToolResult\n\t\t\t{\n");
		Out += TEXT("\t\t\t\t// Runs ON the game thread (the dispatcher guarantees it, docs/ARCHITECTURE.md §4).\n");
		Out += TEXT("\t\t\t\t// Read arguments with Call.GetString/GetInt/GetNumber/GetBool/GetVector.\n");
		Out += SkillsIndentBody(Spec.Body);
		Out += TEXT("\t\t\t});\n");
		Out += TEXT("\t}\n\n");
		Out += TEXT("\tstatic const FUnrealMcpGeneratedSkillRegistrar Registrar(&Register);\n");
		Out += TEXT("}\n");
		return Out;
	}

	FString GetGeneratedSkillsDir()
	{
		const TSharedPtr<IPlugin> Plugin = IPluginManager::Get().FindPlugin(TEXT("UnrealMCP"));
		if (!Plugin.IsValid())
			return FString();

		// The editor module's Private/Tools folder is the anchor: if THAT is missing, this install carries no
		// C++ source (a precompiled / Fab install), and writing a .cpp anywhere would be writing into a folder
		// no build will ever compile.
		const FString ToolsDir = FPaths::ConvertRelativePathToFull(
			Plugin->GetBaseDir() / TEXT("Source") / TEXT("UnrealMcpEditor") / TEXT("Private") / TEXT("Tools"));
		if (!FPaths::DirectoryExists(ToolsDir))
			return FString();

		return ToolsDir / TEXT("Skills");
	}

	// --- Registration ------------------------------------------------------------------------------

	void Register(FUnrealMcpToolRegistry& Registry)
	{
		FUnrealMcpToolRegistry* RegistryPtr = &Registry;

		Registry.Tool(SkillCreateToolId)
			.Title(TEXT("Skill (Tool) / Create"))
			.Description(TEXT(
				"Create a new skill (MCP tool) for the Unreal Editor by generating a C++ source file into the "
				"UnrealMCP plugin's editor module. Unlike Unity (which hot-compiles a new .cs on domain reload), "
				"Unreal C++ needs a BUILD: the file is written and self-registers, but the tool is NOT callable "
				"until the editor is rebuilt (Live Coding, or close the editor and rebuild the project). The "
				"result always says so explicitly.\n"
				"\n"
				"'toolId' is the kebab-case id the AI will call ('my-skill'). 'body' is the C++ statements of the "
				"handler; it runs ON the game thread and must end with a `return FUnrealMcpToolResult::Success(...)` "
				"or `::Error(...)`. Read arguments through the `Call` object: Call.GetString(TEXT(\"name\")), "
				"Call.GetInt, Call.GetNumber, Call.GetBool, Call.GetVector, Call.Has. Build structured output with "
				"`TSharedPtr<FJsonObject> Structured = MakeShared<FJsonObject>();` and pass it as the second "
				"argument of Success().\n"
				"\n"
				"Sample body:\n"
				"  const FString Name = Call.GetString(TEXT(\"name\"));\n"
				"  if (Name.IsEmpty())\n"
				"    return FUnrealMcpToolResult::Error(TEXT(\"'name' is required.\"));\n"
				"  TSharedPtr<FJsonObject> Structured = MakeShared<FJsonObject>();\n"
				"  Structured->SetStringField(TEXT(\"echo\"), Name);\n"
				"  return FUnrealMcpToolResult::Success(Name, Structured);\n"
				"\n"
				"Only the plugin's own editor module is written to — never a game module, because a game module "
				"that depends on UnrealMcpRuntime overrides a consumer's TargetDenyList and drags the plugin into "
				"packaged builds. A precompiled (marketplace) install has no C++ source on disk and is refused."))
			.SkillDescription(TEXT(
				"Create a new skill (MCP tool) for the Unreal Editor by generating a self-registering C++ file into "
				"the UnrealMCP plugin's editor module. The tool becomes callable only after the editor is REBUILT "
				"(Live Coding or a project rebuild) — the result reports that explicitly."))
			.ParamString(TEXT("toolId"), TEXT("Kebab-case tool id the AI will call, e.g. 'my-skill'."), EUnrealMcpParamRequirement::Required)
			.ParamString(TEXT("description"), TEXT("Full tool description shown to the AI."), EUnrealMcpParamRequirement::Required)
			.ParamString(TEXT("body"), TEXT("C++ statements of the handler body; must return a FUnrealMcpToolResult."), EUnrealMcpParamRequirement::Required)
			.ParamString(TEXT("title"), TEXT("Human label. Defaults to a Title-Cased form of 'toolId'."))
			.ParamString(TEXT("skillDescription"), TEXT("Optional SHORT description for the generated SKILL.md front-matter."))
			.Param(TEXT("params"), TEXT("array"), TEXT("Declared parameters."), EUnrealMcpParamRequirement::Optional, SkillsMakeParamsSchema())
			.ParamBool(TEXT("readOnlyHint"), TEXT("Mark the new tool read-only (it does not modify state). Default false."))
			.ParamBool(TEXT("destructiveHint"), TEXT("Mark the new tool destructive. Default false."))
			.ParamBool(TEXT("idempotentHint"), TEXT("Mark the new tool idempotent. Default false."))
			.ParamBool(TEXT("force"), TEXT("Overwrite an existing generated file for the same tool id. Default false."))
			// SYSTEM surface (§2.4), matching Unity's unity-skill-create: skill AUTHORING is host plumbing driven
			// by the CLI / desktop app, not a capability an arbitrary AI agent should find in tools/list.
			.ToolType(EUnrealMcpToolType::System)
			.Handle([RegistryPtr](const FUnrealMcpToolCall& Call) -> FUnrealMcpToolResult
			{
				FSkillSpec Spec;
				Spec.ToolId = Call.GetString(TEXT("toolId")).TrimStartAndEnd();
				Spec.Title = Call.GetString(TEXT("title")).TrimStartAndEnd();
				Spec.Description = Call.GetString(TEXT("description"));
				Spec.SkillDescription = Call.GetString(TEXT("skillDescription"));
				Spec.Body = Call.GetString(TEXT("body"));
				Spec.bReadOnlyHint = Call.GetBool(TEXT("readOnlyHint"), false);
				Spec.bDestructiveHint = Call.GetBool(TEXT("destructiveHint"), false);
				Spec.bIdempotentHint = Call.GetBool(TEXT("idempotentHint"), false);

				FString Error;
				if (!SkillsParseParams(Call, Spec.Params, Error))
					return FUnrealMcpToolResult::Error(Error);
				if (!ValidateSkillSpec(Spec, Error))
					return FUnrealMcpToolResult::Error(Error);

				// Refuse up front: a live collision reported here is far clearer than one surfaced only as a
				// warning at the NEXT boot, when the generated skill's extension scope rejects it first-wins
				// ("extensions may not shadow core") and the tool silently never appears.
				if (RegistryPtr != nullptr && RegistryPtr->HasTool(Spec.ToolId))
				{
					return FUnrealMcpToolResult::Error(FString::Printf(
						TEXT("A tool named '%s' is already registered. Pick a different 'toolId'."), *Spec.ToolId));
				}

				const FString SkillsDir = GetGeneratedSkillsDir();
				if (SkillsDir.IsEmpty())
				{
					return FUnrealMcpToolResult::Error(TEXT(
						"This Unreal-MCP install has no C++ source on disk (a precompiled / marketplace install), so a "
						"generated skill could never be compiled. Install the plugin from source to author skills."));
				}

				const FString FileName = SkillFileNameFromToolId(Spec.ToolId);
				const FString FullPath = SkillsDir / FileName;
				const bool bExists = FPaths::FileExists(FullPath);
				if (bExists && !Call.GetBool(TEXT("force"), false))
				{
					return FUnrealMcpToolResult::Error(FString::Printf(
						TEXT("'%s' already exists. Pass 'force':true to overwrite it."), *FileName));
				}

				if (!IFileManager::Get().DirectoryExists(*SkillsDir)
					&& !IFileManager::Get().MakeDirectory(*SkillsDir, /*Tree*/ true))
				{
					return FUnrealMcpToolResult::Error(FString::Printf(
						TEXT("Failed to create the generated-skills folder '%s'."), *SkillsDir));
				}

				const FString Source = BuildSkillSourceCode(Spec);
				if (!FFileHelper::SaveStringToFile(Source, *FullPath, FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM))
				{
					return FUnrealMcpToolResult::Error(FString::Printf(
						TEXT("Failed to write '%s'."), *FullPath));
				}

				UE_LOG(LogUnrealMcp, Log, TEXT("[Unreal-MCP] generated skill '%s' -> %s (rebuild required)."),
					*Spec.ToolId, *FullPath);

				TSharedPtr<FJsonObject> Structured = MakeShared<FJsonObject>();
				Structured->SetStringField(TEXT("toolId"), Spec.ToolId);
				Structured->SetStringField(TEXT("file"), FullPath);
				Structured->SetStringField(TEXT("module"), TEXT("UnrealMcpEditor"));
				Structured->SetStringField(TEXT("symbol"), SkillSymbolFromToolId(Spec.ToolId));
				Structured->SetBoolField(TEXT("overwritten"), bExists);
				// The load-bearing field: NEVER report the tool as live. It exists in source only.
				Structured->SetBoolField(TEXT("rebuildRequired"), true);
				Structured->SetBoolField(TEXT("callable"), false);
				Structured->SetStringField(TEXT("nextStep"), TEXT(
					"Rebuild the editor to load the new tool: trigger Live Coding (Ctrl+Alt+F11) or close the editor "
					"and rebuild the project. Until then the tool is NOT registered and calling it will fail."));

				return FUnrealMcpToolResult::Success(FString::Printf(
					TEXT("%s '%s' as %s. REBUILD REQUIRED: the tool exists in C++ source but is NOT callable yet — "
					     "trigger Live Coding or rebuild the editor, then it registers itself automatically."),
					bExists ? TEXT("Regenerated") : TEXT("Generated"), *Spec.ToolId, *FileName),
					Structured);
			});
	}
}
